export const cards = [
  {
    id: 1,
    cover: "../../src/assets/carnival-1.png",
    title: "O Python do vovô não sobe mais",
    text: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.",
    location: "São Paulo - SP",
  },
  {
    id: 2,
    cover: "../../src/assets/carnival-2.png",
    title: "Todo mundo null",
    text: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.",
    location: "Florianópolis - SC",
  },
  {
    id: 3,
    cover: "../../src/assets/carnival-3.png",
    title: "Hoje dou exception",
    text: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.",
    location: "Curitiba - PR",
  },
  {
    id: 4,
    cover: "../../src/assets/carnival-4.png",
    title: "Manda Node",
    text: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.",
    location: "Salvador - BA",
  },
  {
    id: 5,
    cover: "../../src/assets/carnival-5.png",
    title: "Só no back-end",
    text: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.",
    location: "São Paulo - SP",
  },
  {
    id: 6,
    cover: "../../src/assets/carnival-6.png",
    title: "Esse anel não é de Ruby",
    text: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.",
    location: "São Paulo - SP",
  },
  {
    id: 7,
    cover: "../../src/assets/carnival-7.png",
    title: "Pimenta no C# dos outros é refresco",
    text: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.",
    location: "Rio de Janeiro - RJ",
  },
  {
    id: 8,
    cover: "../../src/assets/carnival-8.png",
    title: "EnCACHE aqui",
    text: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.",
    location: "Porto Alegre - RS",
  },
  {
    id: 9,
    cover: "../../src/assets/carnival-9.png",
    title: "Não valho nada mas JAVA li",
    text: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.",
    location: "São Paulo - SP",
  },
];
